'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import type { SortableSelectorItem } from '@/gradian-ui/form-builder/form-elements';
import { FormSchema, CardSection, FormField } from '../types/form-schema';
import { Plus, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { motion, AnimatePresence } from 'framer-motion';
import { IconRenderer } from '@/gradian-ui/shared/utils/icon-renderer';
import { CardSectionEditor } from './CardSectionEditor';

interface CardMetadataTabProps {
  schema: FormSchema;
  onUpdate: (updates: Partial<FormSchema>) => void;
}

// Convert title to camelCase ID (similar to labelToCamelCase in FieldEditor)
const titleToId = (title: string): string => {
  if (!title) return '';
  
  return title
    .trim()
    .replace(/[^\w\s-]/g, '') // Remove special characters
    .split(/[\s_-]+/) // Split on spaces, underscores, or hyphens
    .map((word, index) => {
      if (index === 0) {
        return word.toLowerCase();
      }
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join('');
};

export function CardMetadataTab({ schema, onUpdate }: CardMetadataTabProps) {
  const [customSectionIds, setCustomSectionIds] = useState<Record<string, boolean>>({});
  const [editingSectionId, setEditingSectionId] = useState<string | null>(null);
  const cardMetadata = schema.cardMetadata || [];

  const allFields = schema.fields || [];
  const availableFields = allFields.filter(f => !f.inactive);

  const addCardSection = () => {
    const defaultTitle = 'New Card Section';
    const autoGeneratedId = titleToId(defaultTitle) || `card-section-${Date.now()}`;
    const newSection: CardSection = {
      id: autoGeneratedId,
      title: defaultTitle,
      colSpan: 1,
      fieldIds: [],
    };
    onUpdate({ cardMetadata: [...cardMetadata, newSection] });
    setEditingSectionId(newSection.id);
  };

  const updateCardSection = (sectionId: string, updates: Partial<CardSection>) => {
    const updated = cardMetadata.map(section =>
      section.id === sectionId ? { ...section, ...updates } : section
    );
    onUpdate({ cardMetadata: updated });

    if (updates.id && updates.id !== sectionId) {
      setEditingSectionId(prev => (prev === sectionId ? updates.id || prev : prev));
      setCustomSectionIds(prev => {
        if (!(sectionId in prev)) {
          return prev;
        }
        const { [sectionId]: value, ...rest } = prev;
        return { ...rest, [updates.id!]: value };
      });
    }
  };

  const handleTitleChange = (sectionId: string, newTitle: string) => {
    const section = cardMetadata.find(s => s.id === sectionId);
    if (!section) return;

    // Auto-generate ID from title if ID hasn't been manually edited
    if (!customSectionIds[sectionId]) {
      const autoGeneratedId = titleToId(newTitle);
      if (autoGeneratedId) {
        updateCardSection(sectionId, { title: newTitle, id: autoGeneratedId });
        return;
      }
    }
    
    updateCardSection(sectionId, { title: newTitle });
  };

  const handleIdChange = (sectionId: string, newId: string) => {
    setCustomSectionIds(prev => ({ ...prev, [sectionId]: true }));
    updateCardSection(sectionId, { id: newId });
  };

  const handleIdCustomModeChange = (sectionId: string, isCustom: boolean) => {
    setCustomSectionIds(prev => ({ ...prev, [sectionId]: isCustom }));
    
    if (!isCustom) {
      // Reset to auto-generated ID when turning customization off
      const section = cardMetadata.find(s => s.id === sectionId);
      if (section) {
        const autoGeneratedId = titleToId(section.title || '');
        if (autoGeneratedId) {
          updateCardSection(sectionId, { id: autoGeneratedId });
        }
      }
    }
  };

  const deleteCardSection = (sectionId: string) => {
    const updated = cardMetadata.filter(section => section.id !== sectionId);
    onUpdate({ cardMetadata: updated });
    setEditingSectionId(prev => (prev === sectionId ? null : prev));
  };


  const convertFieldsToSelectorItems = (fields: FormField[]): SortableSelectorItem[] => {
    return fields.map(field => {
      // Check if field has badge-related properties
      const badgeVariant = (field as any).badgeVariant;
      const fieldColor = (field as any).color;
      const optionColor = field.options?.find(opt => opt.color)?.color;
      
      return {
        id: field.id,
        label: field.label || field.name,
        icon: field.icon ? <IconRenderer iconName={field.icon} className="h-3 w-3" /> : undefined,
        color: badgeVariant || fieldColor || optionColor,
      };
    });
  };

  const getSelectedFields = (section: CardSection): SortableSelectorItem[] => {
    const fieldIds = section.fieldIds || [];
    const selectedFields = fieldIds
      .map(id => availableFields.find(f => f.id === id))
      .filter((f): f is FormField => f !== undefined);
    return convertFieldsToSelectorItems(selectedFields);
  };

  const getAvailableFields = (section: CardSection): SortableSelectorItem[] => {
    const fieldIds = section.fieldIds || [];
    const unselectedFields = availableFields.filter(f => !fieldIds.includes(f.id));
    return convertFieldsToSelectorItems(unselectedFields);
  };

  const handleFieldSelectionChange = (sectionId: string, selectedItems: SortableSelectorItem[]) => {
    const fieldIds = selectedItems.map(item => item.id);
    updateCardSection(sectionId, { fieldIds });
  };

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <CardTitle>Card Metadata</CardTitle>
              <Badge variant="secondary" className="text-xs px-2 py-0.5">
                {cardMetadata.length} {cardMetadata.length === 1 ? 'section' : 'sections'}
              </Badge>
            </div>
            <Button onClick={addCardSection} size="sm" variant="outline">
              <Plus className="h-4 w-4 mr-2" />
              Add Section
            </Button>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {cardMetadata.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              <p>No card sections defined. Add a section to configure how cards are displayed in list views.</p>
            </div>
          ) : (
            <AnimatePresence mode="popLayout">
              {cardMetadata.map((section, index) => (
                <motion.div
                  key={section.id}
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10, height: 0 }}
                  transition={{
                    duration: 0.3,
                    delay: index * 0.05,
                    ease: [0.4, 0, 0.2, 1],
                  }}
                  layout
                >
                  <Card className="border-gray-200">
                    <CardHeader className="pb-4">
                      <div className="flex items-center justify-between gap-3 flex-wrap">
                        <div>
                          <CardTitle className="text-base">
                            {section.title || 'Untitled Section'}
                          </CardTitle>
                          <div className="flex items-center gap-2 mt-1 text-sm text-muted-foreground">
                            <Badge variant="secondary" className="text-xs px-2 py-0.5">
                              {section.fieldIds?.length || 0}{' '}
                              {section.fieldIds?.length === 1 ? 'field' : 'fields'}
                            </Badge>
                            <span>• Column span: {section.colSpan || 1}</span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setEditingSectionId(section.id)}
                          >
                            Edit Section
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => deleteCardSection(section.id)}
                            className="text-red-600 hover:text-red-700"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                  </Card>
                </motion.div>
              ))}
            </AnimatePresence>
          )}
        </CardContent>
      </Card>
      {editingSectionId && (() => {
        const editingSection = cardMetadata.find((s) => s.id === editingSectionId);
        if (!editingSection) {
          return null;
        }
        return (
          <CardSectionEditor
            section={editingSection}
            availableFields={getAvailableFields(editingSection)}
            selectedFields={getSelectedFields(editingSection)}
            onTitleChange={(value) => handleTitleChange(editingSection.id, value)}
            onIdChange={(value) => handleIdChange(editingSection.id, value)}
            isCustomId={customSectionIds[editingSection.id] || false}
            onCustomModeChange={(isCustom) => handleIdCustomModeChange(editingSection.id, isCustom)}
            onUpdate={(updates) => updateCardSection(editingSection.id, updates)}
            onFieldSelectionChange={(items) => handleFieldSelectionChange(editingSection.id, items)}
            onDelete={() => {
              deleteCardSection(editingSection.id);
              setEditingSectionId(null);
            }}
            onClose={() => setEditingSectionId(null)}
          />
        );
      })()}
    </div>
  );
}

