'use client';

import { useEffect, useMemo, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import type { SortableSelectorItem } from '@/gradian-ui/form-builder/form-elements';
import { FormSchema, CardSection, FormField } from '../types/form-schema';
import { Pencil, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { motion, AnimatePresence } from 'framer-motion';
import { IconRenderer } from '@/gradian-ui/shared/utils/icon-renderer';
import { CardSectionEditor } from './CardSectionEditor';
import { AddButtonFull } from '@/gradian-ui/form-builder/form-elements/components/AddButtonFull';
import { ConfirmationMessage } from '@/gradian-ui/form-builder';
import { ensureKebabCase } from '@/gradian-ui/shared/utils/text-utils';

interface CardMetadataTabProps {
  schema: FormSchema;
  onUpdate: (updates: Partial<FormSchema>) => void;
}

export function CardMetadataTab({ schema, onUpdate }: CardMetadataTabProps) {
  const [customSectionIds, setCustomSectionIds] = useState<Record<string, boolean>>({});
  const [editingSectionId, setEditingSectionId] = useState<string | null>(null);
  const [deleteConfirmSectionId, setDeleteConfirmSectionId] = useState<string | null>(null);
  const [editingSectionDraft, setEditingSectionDraft] = useState<CardSection | null>(null);
  const [editingCustomId, setEditingCustomId] = useState(false);
  const cardMetadata = schema.cardMetadata || [];

  const allFields = schema.fields || [];
  const availableFields = allFields.filter(f => !f.inactive);

  const addCardSection = () => {
    const defaultTitle = 'New Card Section';
    const autoGeneratedId = ensureKebabCase(defaultTitle, 'card-section');
    const newSection: CardSection = {
      id: autoGeneratedId,
      title: defaultTitle,
      colSpan: 1,
      fieldIds: [],
    };
    onUpdate({ cardMetadata: [...cardMetadata, newSection] });
    setEditingSectionId(newSection.id);
  };

  const updateCardSection = (sectionId: string, updates: Partial<CardSection>) => {
    const updated = cardMetadata.map(section =>
      section.id === sectionId ? { ...section, ...updates } : section
    );
    onUpdate({ cardMetadata: updated });

    if (updates.id && updates.id !== sectionId) {
      setEditingSectionId(prev => (prev === sectionId ? updates.id || prev : prev));
      setCustomSectionIds(prev => {
        if (!(sectionId in prev)) {
          return prev;
        }
        const { [sectionId]: value, ...rest } = prev;
        return { ...rest, [updates.id!]: value };
      });
    }
  };

  useEffect(() => {
    if (!editingSectionId) {
      setEditingSectionDraft(null);
      return;
    }
    const section = cardMetadata.find((s) => s.id === editingSectionId);
    if (section) {
      setEditingSectionDraft({ ...section });
      setEditingCustomId(customSectionIds[section.id] || false);
    } else {
      setEditingSectionDraft(null);
    }
  }, [editingSectionId, cardMetadata, customSectionIds]);

  const updateDraftSection = (updates: Partial<CardSection>) => {
    setEditingSectionDraft((prev) => (prev ? { ...prev, ...updates } : prev));
  };

  const handleDraftTitleChange = (newTitle: string) => {
    if (!editingSectionDraft) return;
    if (!editingCustomId) {
      const autoGeneratedId = ensureKebabCase(newTitle, 'card-section');
      updateDraftSection({ title: newTitle, id: autoGeneratedId });
    } else {
      updateDraftSection({ title: newTitle });
    }
  };

  const handleDraftIdChange = (newId: string) => {
    setEditingCustomId(true);
    updateDraftSection({ id: newId });
  };

  const handleDraftCustomModeChange = (isCustom: boolean) => {
    setEditingCustomId(isCustom);
    if (!isCustom) {
      const autoGeneratedId = ensureKebabCase(editingSectionDraft?.title || '', 'card-section');
      updateDraftSection({ id: autoGeneratedId });
    }
  };

  const deleteCardSection = (sectionId: string) => {
    const updated = cardMetadata.filter(section => section.id !== sectionId);
    onUpdate({ cardMetadata: updated });
    setEditingSectionId(prev => (prev === sectionId ? null : prev));
    setDeleteConfirmSectionId(null);
  };


  const convertFieldsToSelectorItems = (fields: FormField[]): SortableSelectorItem[] => {
    return fields.map(field => {
      const isInactive = Boolean(field?.inactive);
      // Check if field has badge-related properties
      const badgeVariant = (field as any).badgeVariant;
      const fieldColor = (field as any).color;
      const optionColor = field.options?.find(opt => opt.color)?.color;
      const displayLabel = `${field.label || field.name}${isInactive ? ' (inactive)' : ''}`;
      const inactiveColor = 'bg-gray-100 text-gray-500 border border-gray-300';
      
      return {
        id: field.id || field.name || Math.random().toString(36).slice(2),
        label: displayLabel,
        icon: field.icon ? <IconRenderer iconName={field.icon} className="h-3 w-3" /> : undefined,
        color: isInactive ? inactiveColor : (badgeVariant || fieldColor || optionColor),
      };
    });
  };

  const getSelectedFields = (section?: CardSection | null): SortableSelectorItem[] => {
    if (!section) return [];
    const fieldIds = section.fieldIds || [];
    const selectedFields = fieldIds
      .map(id => availableFields.find(f => f.id === id))
      .filter((f): f is FormField => f !== undefined);
    return convertFieldsToSelectorItems(selectedFields);
  };

  const getAvailableFields = (section?: CardSection | null): SortableSelectorItem[] => {
    if (!section) return [];
    const fieldIds = section.fieldIds || [];
    const unselectedFields = availableFields.filter(f => !fieldIds.includes(f.id));
    return convertFieldsToSelectorItems(unselectedFields);
  };

  const handleDraftFieldSelectionChange = (selectedItems: SortableSelectorItem[]) => {
    updateDraftSection({ fieldIds: selectedItems.map((item) => item.id) });
  };

  const handleSaveSection = () => {
    if (!editingSectionId || !editingSectionDraft) return;
    updateCardSection(editingSectionId, editingSectionDraft);
    setCustomSectionIds((prev) => {
      const next = { ...prev };
      const originalId = editingSectionId;
      const finalId = editingSectionDraft.id;
      if (editingCustomId) {
        delete next[originalId];
        if (finalId && finalId !== originalId) {
          delete next[finalId];
        }
        if (finalId) {
          next[finalId] = true;
        }
      } else {
        delete next[originalId];
        if (finalId && finalId !== originalId) {
          delete next[finalId];
        }
      }
      return next;
    });
    setEditingSectionId(null);
  };

  const canSaveDraft = useMemo(() => {
    if (!editingSectionDraft) return false;
    return Boolean(editingSectionDraft.title?.trim() && editingSectionDraft.id?.trim());
  }, [editingSectionDraft]);

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <CardTitle>Card Metadata</CardTitle>
            <Badge variant="secondary" className="text-xs px-2 py-0.5">
              {cardMetadata.length} {cardMetadata.length === 1 ? 'section' : 'sections'}
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {cardMetadata.length === 0 ? (
            <div className="space-y-4 py-6">
              <p className="text-center text-gray-500 dark:text-gray-400">
                No card sections defined. Add a section to configure how cards are displayed in list views.
              </p>
              <AddButtonFull
                label="Add Card Section"
                onClick={addCardSection}
                className="border-dashed"
              />
            </div>
          ) : (
            <AnimatePresence mode="popLayout">
              {cardMetadata.map((section, index) => (
                <motion.div
                  key={section.id}
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10, height: 0 }}
                  transition={{
                    duration: 0.3,
                    delay: index * 0.05,
                    ease: [0.4, 0, 0.2, 1],
                  }}
                  layout
                >
                  <Card className="border-gray-200">
                    <CardHeader className="pb-4">
                      <div className="flex items-center justify-between gap-3 flex-wrap">
                        <div>
                          <CardTitle className="text-base">
                            {section.title || 'Untitled Section'}
                          </CardTitle>
                          <div className="flex items-center gap-2 mt-1 text-sm text-muted-foreground">
                            <Badge variant="secondary" className="text-xs px-2 py-0.5">
                              {section.fieldIds?.length || 0}{' '}
                              {section.fieldIds?.length === 1 ? 'field' : 'fields'}
                            </Badge>
                            <span>• Column span: {section.colSpan || 1}</span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setEditingSectionId(section.id)}
                          >
                            <Pencil className="h-3 w-3 me-2" />
                            Edit Section
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setDeleteConfirmSectionId(section.id)}
                            className="text-red-600 hover:text-red-700"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                  </Card>
                </motion.div>
              ))}
            </AnimatePresence>
          )}
          {cardMetadata.length > 0 && (
            <AddButtonFull
              label="Add Card Section"
              onClick={addCardSection}
              className="border-dashed"
            />
          )}
        </CardContent>
      </Card>
      {editingSectionId && editingSectionDraft && (
        <CardSectionEditor
          section={editingSectionDraft}
          availableFields={getAvailableFields(editingSectionDraft)}
          selectedFields={getSelectedFields(editingSectionDraft)}
          onTitleChange={handleDraftTitleChange}
          onIdChange={handleDraftIdChange}
          isCustomId={editingCustomId}
          onCustomModeChange={handleDraftCustomModeChange}
          onUpdate={updateDraftSection}
          onFieldSelectionChange={handleDraftFieldSelectionChange}
          onDelete={() => {
            if (editingSectionDraft) {
              deleteCardSection(editingSectionDraft.id);
              setEditingSectionId(null);
            }
          }}
          onSave={handleSaveSection}
          saveDisabled={!canSaveDraft}
          onClose={() => setEditingSectionId(null)}
        />
      )}
      <ConfirmationMessage
        isOpen={deleteConfirmSectionId !== null}
        onOpenChange={(open) => {
          if (!open) {
            setDeleteConfirmSectionId(null);
          }
        }}
        title="Delete Card Section"
        message="Are you sure you want to delete this card section? This action cannot be undone, but you can add a new section later."
        variant="destructive"
        buttons={[
          {
            label: 'Cancel',
            variant: 'outline',
            action: () => setDeleteConfirmSectionId(null),
          },
          {
            label: 'Delete',
            variant: 'destructive',
            icon: 'Trash2',
            action: () => {
              if (deleteConfirmSectionId) {
                deleteCardSection(deleteConfirmSectionId);
              }
            },
          },
        ]}
      />
    </div>
  );
}

