'use client';

import { useState, useEffect } from 'react';
import { TextInput, NumberInput, Label, Badge, Switch, ButtonMinimal, Select, Slider } from '@/gradian-ui/form-builder/form-elements';
import { Button } from '@/components/ui/button';
import { Trash2, Edit } from 'lucide-react';
import { FieldEditorProps } from '../types/builder';
import { FIELD_TYPES, ROLES } from '../utils/builder-utils';
import { FormField } from '../types/form-schema';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

// Convert label to camelCase field name
const labelToCamelCase = (label: string): string => {
  if (!label) return '';
  
  return label
    .trim()
    .replace(/[^\w\s-]/g, '') // Remove special characters
    .split(/[\s_-]+/) // Split on spaces, underscores, or hyphens
    .map((word, index) => {
      if (index === 0) {
        return word.toLowerCase();
      }
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join('');
};

export function FieldEditor({
  field,
  onUpdate,
  onDelete,
  sections,
  canMoveUp = false,
  canMoveDown = false,
  onMoveUp,
  onMoveDown,
}: FieldEditorProps) {
  const [showDialog, setShowDialog] = useState(false);
  const [tempField, setTempField] = useState<Partial<FormField>>(field);
  const [nameManuallyEdited, setNameManuallyEdited] = useState(false);

  useEffect(() => {
    setTempField(field);
    setNameManuallyEdited(false);
  }, [field]);

  const handleSave = () => {
    onUpdate(tempField);
    setShowDialog(false);
  };

  const handleLabelChange = (value: string) => {
    const newLabel = value;
    let newName = tempField.name || '';
    
    // Auto-generate name from label if name hasn't been manually edited
    // or if the current name matches the auto-generated name from the old label
    if (!nameManuallyEdited) {
      const autoGeneratedName = labelToCamelCase(newLabel);
      if (autoGeneratedName) {
        newName = autoGeneratedName;
      }
    }
    
    setTempField({ ...tempField, label: newLabel, name: newName });
  };

  const handleNameChange = (value: string) => {
    setNameManuallyEdited(true);
    setTempField({ ...tempField, name: value });
  };

  return (
    <>
      <div className="w-full flex items-center justify-between">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-1.5">
            <span className="text-sm font-medium truncate text-gray-800">{field.label || 'Unnamed Field'}</span>
            <Badge variant="outline" size="sm" className="text-[10px] px-1.5 py-0">{field.type}</Badge>
            {field.required && <Badge variant="danger" size="sm" className="text-[10px] px-1.5 py-0">Required</Badge>}
          </div>
          <span className="text-[10px] text-gray-400 truncate block mt-0.5">{field.name}</span>
        </div>
        <div className="flex gap-0.5 ml-2 shrink-0">
          <ButtonMinimal
            icon={Edit}
            title="Edit Field"
            color="violet"
            size="md"
            onClick={() => setShowDialog(true)}
          />
          <ButtonMinimal
            icon={Trash2}
            title="Delete Field"
            color="red"
            size="md"
            onClick={onDelete}
          />
        </div>
      </div>

      {showDialog && (
        <Dialog open={showDialog} onOpenChange={(open) => !open && setShowDialog(false)}>
          <DialogContent className="w-[95vw] sm:w-full max-w-3xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Edit Field</DialogTitle>
              <DialogDescription>
                Configure field properties and settings
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-5 py-4">
              <div className="grid grid-cols-2 gap-4">
                <TextInput
                  config={{
                    name: 'label',
                    label: 'Field Label',
                    type: 'text',
                    placeholder: 'Enter field label...'
                  }}
                  value={tempField.label || ''}
                  onChange={handleLabelChange}
                  className="h-9"
                />
                <TextInput
                  config={{
                    name: 'name',
                    label: 'Field Name',
                    type: 'text',
                    placeholder: 'Enter field name...'
                  }}
                  value={tempField.name || ''}
                  onChange={handleNameChange}
                  className="h-9"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Field Type</Label>
                  <Select
                    value={tempField.type || ''}
                    onValueChange={(value) => setTempField({ ...tempField, type: value as any, component: value as any })}
                    options={FIELD_TYPES.map((type) => ({ value: type.value, label: type.label }))}
                  />
                </div>
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Component</Label>
                  <Select
                    value={tempField.component || ''}
                    onValueChange={(value) => setTempField({ ...tempField, component: value as any })}
                    options={FIELD_TYPES.map((type) => ({ value: type.value, label: type.label }))}
                  />
                </div>
              </div>
              <div>
                <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Section</Label>
                <Select
                  value={tempField.sectionId || ''}
                  onValueChange={(value) => setTempField({ ...tempField, sectionId: value })}
                  options={sections.map((section) => ({ value: section.id, label: section.title }))}
                />
              </div>
              <div>
                <TextInput
                  config={{
                    name: 'placeholder',
                    label: 'Placeholder',
                    type: 'text',
                    placeholder: 'Enter placeholder text...'
                  }}
                  value={tempField.placeholder || ''}
                  onChange={(value) => setTempField({ ...tempField, placeholder: value })}
                  className="h-9"
                />
              </div>
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                <Switch
                  config={{ name: `required-${field.id}`, label: 'Required' }}
                  checked={tempField.required || false}
                  onChange={(checked) => setTempField({ ...tempField, required: checked })}
                />
                <Switch
                  config={{ name: `disabled-${field.id}`, label: 'Disabled' }}
                  checked={tempField.disabled || false}
                  onChange={(checked) => setTempField({ ...tempField, disabled: checked })}
                />
                <Switch
                  config={{ name: `readonly-${field.id}`, label: 'Readonly' }}
                  checked={tempField.readonly || false}
                  onChange={(checked) => setTempField({ ...tempField, readonly: checked })}
                />
                <Switch
                  config={{ name: `canCopy-${field.id}`, label: 'Can Copy' }}
                  checked={tempField.canCopy || false}
                  onChange={(checked) => setTempField({ ...tempField, canCopy: checked })}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Role</Label>
                  <Select
                    value={tempField.role || ''}
                    onValueChange={(value) => setTempField({ ...tempField, role: value ? (value as any) : undefined })}
                    options={[
                      { value: '', label: 'None' },
                      ...ROLES.map((role) => ({ value: role.value, label: role.label }))
                    ]}
                  />
                </div>
                <div>
                  <Slider
                    config={{
                      name: 'colSpan',
                      label: 'Column Span',
                    }}
                    value={tempField.colSpan || 1}
                    onChange={(value) => setTempField({ ...tempField, colSpan: value })}
                    min={1}
                    max={4}
                    step={1}
                  />
                </div>
              </div>
            </div>
            <DialogFooter className="flex-col sm:flex-row gap-2">
              <Button variant="outline" onClick={() => setShowDialog(false)} className="w-full sm:w-auto text-sm md:text-base">
                Cancel
              </Button>
              <Button onClick={handleSave} className="w-full sm:w-auto text-sm md:text-base">
                <span className="hidden md:inline">Save Changes</span>
                <span className="md:hidden">Save</span>
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </>
  );
}

