# HTTP Book - Authentication & Password Scenarios
# @name auth_password_tests
# Update `baseUrl`, credentials, and tokens as needed before executing the requests.

@baseUrl = http://localhost:3000
@clientId = development-client-id
@secretKey = development-secret-key
@twoFactorCode = 719807
@userId = 01K9ABA6MQ9K64MY7M4AEBCAP2
@userEmail = abidi.mahyar@gmail.com
###
# Use valid credentials to authenticate and capture the returned access token.
POST {{baseUrl}}/api/auth/login
content-type: application/json

{
  "email": "abidi.mahyar@gmail.com",
  "password": "NewPassword!123"
}

HTTP/1.1 200  - OK
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
set-cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUs5QUJBNk1ROUs2NE1ZN000QUVCQ0FQMiIsImVtYWlsIjoiYWJpZGkubWFoeWFyQGdtYWlsLmNvbSIsIm5hbWUiOiJNYWh5YXIiLCJpYXQiOjE3NjI3NjUxMzEsImV4cCI6MTc2Mjc2ODczMX0.nu-rDkXXgoNIwJF8bO8DTBXIJsw4UYo-xA5OK1FpY5s; Path=/; Expires=Mon, 10 Nov 2025 09:58:51 GMT; Max-Age=3600; HttpOnly; SameSite=lax, refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUs5QUJBNk1ROUs2NE1ZN000QUVCQ0FQMiIsImVtYWlsIjoiYWJpZGkubWFoeWFyQGdtYWlsLmNvbSIsIm5hbWUiOiJNYWh5YXIiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc2Mjc2NTEzMSwiZXhwIjoxNzYzMzY5OTMxfQ.j1HXLbytYy1tqAMORNs1Rzkm5wUZBqpOqM7-u31Y7vA; Path=/; Expires=Mon, 17 Nov 2025 08:58:51 GMT; Max-Age=604800; HttpOnly; SameSite=lax
date: Mon, 10 Nov 2025 08:58:51 GMT
connection: close
transfer-encoding: chunked
###
POST {{baseUrl}}/api/auth/login
content-type: application/json

{
  "email": "",
  "password": ""
}

HTTP/1.1 400  - Bad Request
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 10 Nov 2025 08:56:39 GMT
connection: close
transfer-encoding: chunked
###
POST {{baseUrl}}/api/auth/login
content-type: application/json

{
  "email": "abidi.mahyar@gmail.com",
  "password": "WrongPassword123"
}

HTTP/1.1 401  - Unauthorized
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 10 Nov 2025 08:56:42 GMT
connection: close
transfer-encoding: chunked
###
POST {{baseUrl}}/api/auth/password/change
content-type: application/json

{
  "clientId": "{{clientId}}",
  "secretKey": "{{secretKey}}",
  "username": "{{userEmail}}",
  "currentPassword": "Mm123456",
  "newPassword": "NewPassword!123"
}

HTTP/1.1 400  - Bad Request
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 10 Nov 2025 08:56:56 GMT
connection: close
transfer-encoding: chunked
###
POST {{baseUrl}}/api/auth/password/change
content-type: application/json

{
  "clientId": "{{clientId}}",
  "secretKey": "{{secretKey}}",
  "username": "{{userEmail}}",
  "currentPassword": "",
  "newPassword": ""
}
###
POST {{baseUrl}}/api/auth/2fa/generate
content-type: application/json

{
  "userId": "{{userId}}",
  "clientId": "{{clientId}}",
  "secretKey": "{{secretKey}}",
  "ttlSeconds": 300
}

HTTP/1.1 200  - OK
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 10 Nov 2025 08:57:58 GMT
connection: close
transfer-encoding: chunked
###
POST {{baseUrl}}/api/auth/2fa/validate
content-type: application/json

{
  "userId": "{{userId}}",
  "code": "189593",
  "clientId": "{{clientId}}",
  "secretKey": "{{secretKey}}"
}

HTTP/1.1 410  - Gone
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 10 Nov 2025 08:58:30 GMT
connection: close
transfer-encoding: chunked
###
POST {{baseUrl}}/api/auth/password/reset
content-type: application/json

{
  "username": "{{userEmail}}",
  "code": "157225",
  "password": "NewPassword!123",
  "confirmPassword": "NewPassword!123"
}

HTTP/1.1 410  - Gone
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 10 Nov 2025 08:58:13 GMT
connection: close
transfer-encoding: chunked