// Schema Manager Constants

export const FIELD_TYPES = [
  { value: 'text', label: 'Text' },
  { value: 'email', label: 'Email' },
  { value: 'number', label: 'Number' },
  { value: 'password', label: 'Password' },
  { value: 'textarea', label: 'Textarea' },
  { value: 'select', label: 'Select' },
  { value: 'checkbox', label: 'Checkbox' },
  { value: 'checkbox-list', label: 'Checkbox List' },
  { value: 'radio', label: 'Radio' },
  { value: 'date', label: 'Date' },
  { value: 'datetime-local', label: 'Date Time Local' },
  { value: 'datetime', label: 'Date Time' },
  { value: 'tel', label: 'Phone' },
  { value: 'phone', label: 'Phone (alias)' },
  { value: 'url', label: 'URL' },
  { value: 'file', label: 'File' },
  { value: 'picker', label: 'Picker' },
  { value: 'icon', label: 'Icon' },
  { value: 'icon-input', label: 'Icon Input' },
  { value: 'image-text', label: 'Image Text' },
  { value: 'button', label: 'Button' },
  { value: 'input', label: 'Input' },
  { value: 'avatar', label: 'Avatar' },
  { value: 'color-picker', label: 'Color Picker' },
  { value: 'rating', label: 'Rating' },
  { value: 'badge', label: 'Badge' },
  { value: 'countdown', label: 'Countdown' },
] as const;

export const ROLES = [
  { value: 'title', label: 'Title' },
  { value: 'subtitle', label: 'Subtitle' },
  { value: 'description', label: 'Description' },
  { value: 'image', label: 'Image' },
  { value: 'avatar', label: 'Avatar' },
  { value: 'icon', label: 'Icon' },
  { value: 'rating', label: 'Rating' },
  { value: 'badge', label: 'Badge' },
  { value: 'status', label: 'Status' },
  { value: 'email', label: 'Email' },
  { value: 'location', label: 'Location' },
  { value: 'tel', label: 'Phone' },
  { value: 'duedate', label: 'Due Date' },
  { value: 'code', label: 'Code' },
] as const;

